### ISSUE TITLE
Device factor not found after enabling MFA

### ISSUE THREAD

**Issue by AyushBherwani1998** [tkey/mpc-core-kit-swift#11]
## Description

If we enable the MFA, and re-login it throws device factor not found error even tho if we are using the same device. I did look at the the code, we are [returning "device factor not found"](https://github.com/tkey/mpc-core-kit-swift/blob/7f3b7ef03d71e602182747b8d656cccbb47394b7/Sources/mpc-core-kit-swift/mpcCoreKitSwift.swift#L240) as soon as we don't get the hashedKey. But if we are enabling the MFA, the hashedKey would be deleted and a device factor would be created. IMO, instead of returning error, we should also verify device factor is present or not.

**Comment by himanshuchawla009** [comment]
fixed
