### ISSUE TITLE
Add user info function

### ISSUE THREAD

**Issue by AyushBherwani1998** [tkey/mpc-core-kit-swift#14]
As of the now Swift SDK is missing the user info function. 

Web: https://web3auth.io/docs/sdk/core-kit/mpc-core-kit/usage#get-user-info

**Comment by AyushBherwani1998** [comment]
As of now user info returns a Dictionary, can we return an object similar to core-kit-web? https://web3auth.io/docs/sdk/core-kit/mpc-core-kit/usage#get-user-info

Getting Dictionary is not convenient since as a developer, I wouldn't know what data is coming, and it will defer based on login used.

**Comment by himanshuchawla009** [comment]
this will require change in custom auth, custom auth swift also returns a dictionary. We can release this in next patch version. I think you guys should proceed with releasing version if all bugs are resolved.

**Comment by himanshuchawla009** [comment]
closing as we decided , that we will release typed version along with custom Auth updates
